"use client";

import { useEffect, useMemo, useState } from "react";

type Row = Record<string, any>;
const tabs = ["Today", "Opportunities", "Content", "Replies", "People", "Analytics", "Learning", "Projects", "Research", "Calendar", "Profile", "Approvals"];
const formats = ["short insight", "build update", "problem → solution", "technical lesson", "AI experiment", "product-building story", "opinion", "mini-thread", "case study", "monetization experiment"];
const card: React.CSSProperties = { background: "rgba(255,255,255,.035)", border: "1px solid rgba(255,255,255,.09)", borderRadius: 18, padding: 20 };
const button: React.CSSProperties = { border: "1px solid rgba(255,255,255,.13)", background: "rgba(255,255,255,.06)", color: "inherit", borderRadius: 10, padding: "9px 13px", cursor: "pointer" };
const input: React.CSSProperties = { width: "100%", boxSizing: "border-box", marginTop: 7, marginBottom: 14, padding: "11px 12px", borderRadius: 10, border: "1px solid rgba(255,255,255,.1)", background: "rgba(0,0,0,.2)", color: "inherit" };

async function api<T = Row>(url: string, options?: RequestInit): Promise<T> { const r = await fetch(url, options); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Request failed"); return d; }
const post = (url: string, body: Row) => api(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });

export default function GrowthAgentWorkspace() {
  const [tab, setTab] = useState("Today");
  const [strategy, setStrategy] = useState<Row>({});
  const [content, setContent] = useState<Row>({});
  const [replies, setReplies] = useState<Row>({});
  const [people, setPeople] = useState<Row>({});
  const [analytics, setAnalytics] = useState<Row>({});
  const [calendar, setCalendar] = useState<Row>({});
  const [profile, setProfile] = useState<Row>({});
  const [projects, setProjects] = useState<Row[]>([]);
  const [research, setResearch] = useState<Row[]>([]);
  const [approvals, setApprovals] = useState<Row>({});
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const [projectForm, setProjectForm] = useState({ name: "", description: "", stage: "building", lessons: "", technologies: "", urls: "" });
  const [researchForm, setResearchForm] = useState({ title: "", topic: "", summary: "", source_url: "", relevance_score: 70, momentum_score: 60 });

  async function load() {
    setLoading(true); setMessage("");
    try {
      const [s, c, r, p, a, cal, prof, proj, res, appr] = await Promise.all([
        api<Row>("/api/growth/strategy"), api<Row>("/api/growth/content"), api<Row>("/api/growth/replies"), api<Row>("/api/growth/relationships"), api<Row>("/api/growth/analytics"), api<Row>("/api/growth/calendar"), api<Row>("/api/growth/profile"), api<Row>("/api/growth/projects"), api<Row>("/api/growth/research"), api<Row>("/api/growth/approval"),
      ]);
      setStrategy(s); setContent(c); setReplies(r); setPeople(p); setAnalytics(a); setCalendar(cal); setProfile(prof.profile || {}); setProjects(proj.projects || []); setResearch(res.research || []); setApprovals(appr);
    } catch (e) { setMessage(e instanceof Error ? e.message : "Could not load growth system"); }
    finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);

  async function seedDemo() { try { const d = await post("/api/growth/demo", {}); setMessage(d.message); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Demo seed failed"); } }
  async function generateContent(idea: Row, format = "short insight") { try { await post("/api/growth/content", { action: "generate", idea, format, niche: strategy.profile?.niche, experience: strategy.projects?.map((p: Row) => `${p.name}: ${p.description}`).join("; ") || "my current product build", tone: strategy.profile?.tone }); setMessage("Draft created. Review it before publishing."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Generation failed"); } }
  async function generateReply(o: Row) { try { await post("/api/growth/replies", { opportunity_id: o.id, author_username: o.author_username, topic: o.topic, source_content: o.content, niche: strategy.profile?.niche, experience: strategy.projects?.map((p: Row) => p.name).join(", ") }); setMessage("Reply suggestion created for review."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Reply generation failed"); } }
  async function approve(type: "content" | "reply", id: string) { try { await api(type === "content" ? "/api/growth/content" : "/api/growth/replies", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status: "approved" }) }); setMessage("Approved internally. Nothing was published to X."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Approval failed"); } }
  async function recAction(a: Row, action: "complete" | "save" | "reject") { try { await post("/api/growth/strategy", { action, type: a.type || "analytics", title: a.title, reason: a.reason, score: a.priority, reference_id: a.referenceId }); setMessage(action === "complete" ? "Action marked complete." : `Recommendation ${action}d.`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not record action"); } }
  async function saveProfile() { try { await api("/api/growth/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); setMessage("Growth profile saved."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Profile save failed"); } }
  async function addProject() { try { await post("/api/growth/projects", { ...projectForm, lessons: split(projectForm.lessons), technologies: split(projectForm.technologies), urls: split(projectForm.urls) }); setProjectForm({ name: "", description: "", stage: "building", lessons: "", technologies: "", urls: "" }); setMessage("Project context saved."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Project save failed"); } }
  async function addResearch() { try { await post("/api/growth/research", { ...researchForm, source_type: "manual" }); setResearchForm({ title: "", topic: "", summary: "", source_url: "", relevance_score: 70, momentum_score: 60 }); setMessage("Research signal saved. It can now influence opportunity scoring."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Research save failed"); } }
  const progress = strategy.progress || {};
  const learning = strategy.learning || {};
  const actions = strategy.actions || [];
  const opportunities = strategy.opportunities || [];
  const ideas = strategy.content || [];
  const relationshipRows = strategy.people || strategy.relationships || [];
  const realOnly = analytics.postsAnalyzed || 0;

  return <main style={{ minHeight: "100vh", maxWidth: 1440, margin: "0 auto", padding: "28px 24px 70px" }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: 20, alignItems: "flex-end", marginBottom: 22 }}>
      <div><div style={{ opacity: .48, fontSize: 11, letterSpacing: 2 }}>X GROWTH AGENT · GROWTH OPERATING SYSTEM</div><h1 style={{ fontSize: 40, lineHeight: 1.05, margin: "8px 0" }}>Good morning, {strategy.account?.name || "builder"}.</h1><div style={{ opacity: .62 }}>Decide what is worth doing today. Create useful work. Build real relationships.</div></div>
      <div style={{ display: "flex", gap: 8 }}><button style={button} onClick={seedDemo}>Load demo data</button><button style={button} onClick={load}>{loading ? "Refreshing…" : "Refresh"}</button></div>
    </header>
    {message && <div style={{ ...card, marginBottom: 16 }}>{message}</div>}
    <div style={{ ...card, marginBottom: 16, display: "flex", justifyContent: "space-between", gap: 14, flexWrap: "wrap" }}><div><b>Data mode</b><div style={{ opacity: .6, marginTop: 4 }}>{strategy.dataStatus?.realPosts || 0} real posts · {strategy.dataStatus?.demoPosts || 0} demo posts · {strategy.dataStatus?.realMetrics || 0} real metric snapshots · {strategy.dataStatus?.demoMetrics || 0} demo snapshots</div></div><div><b>{strategy.dataStatus?.xStatus === "limited" ? "X connected · API limited" : strategy.dataStatus?.xStatus || "X unavailable"}</b><div style={{ opacity: .6, marginTop: 4 }}>{strategy.dataStatus?.lastSuccessfulSyncAt ? `Last successful sync ${new Date(strategy.dataStatus.lastSuccessfulSyncAt).toLocaleString()}` : "No successful sync yet"}</div></div></div>
    <nav style={{ display: "flex", flexWrap: "wrap", gap: 7, marginBottom: 18 }}>{tabs.map((x) => <button key={x} style={{ ...button, background: tab === x ? "rgba(255,255,255,.15)" : button.background }} onClick={() => setTab(x)}>{x}</button>)}</nav>

    {tab === "Today" && <Today strategy={strategy} actions={actions} progress={progress} learning={learning} opportunities={opportunities} ideas={ideas} onGenerateContent={generateContent} onGenerateReply={generateReply} onAction={recAction} />}
    {tab === "Opportunities" && <Section title="Opportunity engine" subtitle="Relevance, momentum, audience fit, conversation quality and your ability to add value.">{opportunities.map((o: Row) => <Opportunity key={o.id} o={o} onReply={() => generateReply(o)} onStatus={(status) => api("/api/growth/opportunities", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: o.id, status }) }).then(load)} />)}{!opportunities.length && <Empty text="No opportunities yet. Load labelled demo data or add a manual opportunity through the API." />}</Section>}
    {tab === "Content" && <ContentPanel content={content} ideas={ideas} onGenerate={generateContent} onApprove={(id) => approve("content", id)} />}
    {tab === "Replies" && <Section title="Reply intelligence" subtitle="Useful, contextual and human. Approval is required.">{(replies.replies || []).map((r: Row) => <Draft key={r.id} draft={{ ...r, body: r.reply }} onApprove={() => approve("reply", r.id)} />)}{!(replies.replies || []).length && <Empty text="Generate a reply from an opportunity first." />}</Section>}
    {tab === "People" && <People rows={relationshipRows} />}
    {tab === "Analytics" && <Analytics data={analytics} />}
    {tab === "Learning" && <Learning data={learning} analytics={analytics} />}
    {tab === "Projects" && <Section title="First-hand project context" subtitle="The agent should write from what you have actually built, tested and learned."><div style={{ ...card, marginBottom: 14 }}><h3>Add a project</h3><Field label="Name" value={projectForm.name} onChange={(v) => setProjectForm({ ...projectForm, name: v })} /><Field label="Description" value={projectForm.description} onChange={(v) => setProjectForm({ ...projectForm, description: v })} /><Field label="Stage" value={projectForm.stage} onChange={(v) => setProjectForm({ ...projectForm, stage: v })} /><Field label="Lessons (comma separated)" value={projectForm.lessons} onChange={(v) => setProjectForm({ ...projectForm, lessons: v })} /><Field label="Technologies" value={projectForm.technologies} onChange={(v) => setProjectForm({ ...projectForm, technologies: v })} /><Field label="URLs" value={projectForm.urls} onChange={(v) => setProjectForm({ ...projectForm, urls: v })} /><button style={button} onClick={addProject}>Save project</button></div>{projects.map((p) => <div key={p.id} style={{ ...card, marginBottom: 10 }}><h3>{p.name}</h3><div style={{ opacity: .65 }}>{p.stage} · {p.technologies?.join(", ")}</div><p>{p.description}</p>{p.lessons?.length > 0 && <small>Lessons: {p.lessons.join(" · ")}</small>}</div>)}{!projects.length && <Empty text="Add the products and experiments you are actually building. This improves first-hand content quality." />}</Section>}
    {tab === "Research" && <Section title="Research signals" subtitle="Add public/manual research without pretending the app has live X access. These signals can influence opportunity scoring."><div style={{ ...card, marginBottom: 14 }}><Field label="Title" value={researchForm.title} onChange={(v) => setResearchForm({ ...researchForm, title: v })} /><Field label="Topic" value={researchForm.topic} onChange={(v) => setResearchForm({ ...researchForm, topic: v })} /><Field label="Summary" value={researchForm.summary} onChange={(v) => setResearchForm({ ...researchForm, summary: v })} /><Field label="Source URL (optional)" value={researchForm.source_url} onChange={(v) => setResearchForm({ ...researchForm, source_url: v })} /><Field label="Relevance score" value={String(researchForm.relevance_score)} type="number" onChange={(v) => setResearchForm({ ...researchForm, relevance_score: Number(v) })} /><Field label="Momentum score" value={String(researchForm.momentum_score)} type="number" onChange={(v) => setResearchForm({ ...researchForm, momentum_score: Number(v) })} /><button style={button} onClick={addResearch}>Save research signal</button></div>{research.map((r) => <div key={r.id} style={{ ...card, marginBottom: 10 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><h3>{r.title}</h3><b>{r.relevance_score}/100</b></div><div style={{ opacity: .55 }}>{r.topic} · momentum {r.momentum_score}/100</div><p>{r.summary}</p>{r.source_url && <small>{r.source_url}</small>}</div>)}{!research.length && <Empty text="No research signals yet." />}</Section>}
    {tab === "Calendar" && <Section title="Content calendar" subtitle="Plan content without forcing a rigid schedule or auto-publishing.">{(calendar.calendar || []).map((x: Row) => <div key={x.id} style={{ ...card, marginBottom: 10 }}><b>{new Date(x.planned_date).toLocaleDateString()}</b><div style={{ opacity: .65 }}>{x.pillar} · {x.format} · {x.status}</div><p>{x.notes}</p></div>)}{!(calendar.calendar || []).length && <Empty text="No planned content yet." />}</Section>}
    {tab === "Profile" && <Section title="Growth profile" subtitle="Your context controls scoring and generation."><Field label="Niche" value={profile.niche || ""} onChange={(v) => setProfile({ ...profile, niche: v })} /><Field label="Target followers" value={String(profile.target_followers || 1000)} type="number" onChange={(v) => setProfile({ ...profile, target_followers: Number(v) })} /><Field label="Content pillars (comma separated)" value={(profile.content_pillars || []).join(", ")} onChange={(v) => setProfile({ ...profile, content_pillars: split(v) })} /><Field label="Tone" value={(profile.tone || []).join(", ")} onChange={(v) => setProfile({ ...profile, tone: split(v) })} /><Field label="Avoid" value={(profile.avoid_topics || []).join(", ")} onChange={(v) => setProfile({ ...profile, avoid_topics: split(v) })} /><button style={button} onClick={saveProfile}>Save profile</button></Section>}
    {tab === "Approvals" && <Section title="Approval center" subtitle="Approval is internal workflow state. It does not publish to X."><h3>Content</h3>{(approvals.content || []).map((x: Row) => <Draft key={x.id} draft={x} onApprove={() => approve("content", x.id)} />)}<h3>Replies</h3>{(approvals.replies || []).map((x: Row) => <Draft key={x.id} draft={{ ...x, body: x.reply }} onApprove={() => approve("reply", x.id)} />)}</Section>}
  </main>;
}

function split(value: string) { return value.split(",").map((x) => x.trim()).filter(Boolean); }
function Section({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section style={card}><h2 style={{ margin: "0 0 5px" }}>{title}</h2><p style={{ opacity: .58, marginTop: 0 }}>{subtitle}</p>{children}</section>; }
function Empty({ text }: { text: string }) { return <div style={{ ...card, opacity: .7, marginTop: 10 }}>{text}</div>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (v: string) => void; type?: string }) { return <label style={{ display: "block", opacity: .8 }}>{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} style={input} /></label>; }
function Metric({ label, value, sub }: { label: string; value: React.ReactNode; sub: string }) { return <div style={card}><div style={{ opacity: .5 }}>{label}</div><div style={{ fontSize: 29, fontWeight: 750, margin: "7px 0" }}>{value}</div><small style={{ opacity: .5 }}>{sub}</small></div>; }
function Today({ strategy, actions, progress, learning, opportunities, ideas, onGenerateContent, onGenerateReply, onAction }: Row) { return <><div style={{ display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: 12 }}><Metric label="Followers" value={progress.followers ?? 0} sub={`${progress.percent ?? 0}% of ${progress.target ?? 1000}`} /><Metric label="Remaining" value={progress.remaining ?? 0} sub="to target" /><Metric label="Today's actions" value={actions.length} sub="prioritized, approval-first" /><Metric label="Learning" value={learning.sufficient ? "Early signal" : "Not enough data"} sub={learning.message || "Need 5+ real posts"} /></div><div style={{ display: "grid", gridTemplateColumns: "1.45fr 1fr", gap: 12, marginTop: 12 }}><div style={card}><h2>What should I do today?</h2>{actions.map((a: Row) => <div key={`${a.type}-${a.referenceId}`} style={{ borderTop: "1px solid rgba(255,255,255,.08)", padding: "15px 0" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><div><b>{a.title}</b><p style={{ opacity: .62, margin: "6px 0" }}>{a.reason}</p></div><strong>{a.priority}/100</strong></div><div style={{ display: "flex", gap: 7 }}><button style={button} onClick={() => onAction(a, "complete")}>Done</button><button style={button} onClick={() => onAction(a, "save")}>Save</button><button style={button} onClick={() => onAction(a, "reject")}>Skip</button></div></div>)}{!actions.length && <Empty text="No recommendations yet." />}</div><div style={card}><h2>Progress to 1,000</h2><div style={{ fontSize: 52, fontWeight: 800 }}>{progress.followers ?? 0}</div><div style={{ opacity: .55 }}>{progress.remaining ?? 0} followers remaining</div><div style={{ height: 9, background: "rgba(255,255,255,.08)", borderRadius: 20, margin: "18px 0" }}><div style={{ width: `${Math.min(100, progress.percent ?? 0)}%`, height: "100%", background: "currentColor", borderRadius: 20 }} /></div><p style={{ opacity: .62 }}>{strategy.guardrails?.message}</p></div></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginTop: 12 }}><div style={card}><h2>🔥 Top opportunities</h2>{opportunities.slice(0, 3).map((o: Row) => <Opportunity key={o.id} o={o} onReply={() => onGenerateReply(o)} />)}</div><div style={card}><h2>✍️ Content opportunities</h2>{ideas.slice(0, 3).map((i: Row) => <Idea key={i.id} idea={i} onClick={() => onGenerateContent(i)} />)}</div></div></> }
function Opportunity({ o, onReply, onStatus }: { o: Row; onReply: () => void; onStatus?: (status: string) => void }) { return <article style={{ borderTop: "1px solid rgba(255,255,255,.08)", padding: "15px 0" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><b>@{String(o.author_username || "").replace(/^@/, "")}</b><span style={{ opacity: .55 }}> · {o.topic}</span><p style={{ margin: "7px 0", opacity: .75 }}>{o.content}</p><small style={{ opacity: .55 }}>{o.reason}</small></div><strong>{o.opportunity_score}/100</strong></div><div style={{ display: "flex", gap: 7, marginTop: 10, flexWrap: "wrap" }}><button style={button} onClick={onReply}>Generate reply</button>{onStatus && <><button style={button} onClick={() => onStatus("saved")}>Save</button><button style={button} onClick={() => onStatus("acted")}>Mark acted</button><button style={button} onClick={() => onStatus("ignored")}>Skip</button></>}</div></article>; }
function Idea({ idea, onClick }: { idea: Row; onClick: () => void }) { return <article style={{ borderTop: "1px solid rgba(255,255,255,.08)", padding: "15px 0" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><b>{idea.title}</b><p style={{ margin: "7px 0", opacity: .62 }}>{idea.reason}</p><small style={{ opacity: .55 }}>{idea.angle}</small></div><strong>{idea.score}/100</strong></div><button style={{ ...button, marginTop: 10 }} onClick={onClick}>Generate draft</button></article>; }
function Draft({ draft, onApprove }: { draft: Row; onApprove: () => void }) { return <article style={{ ...card, margin: "10px 0" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><b>{draft.format || "reply"}</b><span style={{ opacity: .55 }}>{draft.status}</span></div><p style={{ whiteSpace: "pre-wrap", lineHeight: 1.6 }}>{draft.body}</p>{draft.status === "draft" || draft.status === "pending" ? <button style={button} onClick={onApprove}>Approve</button> : null}</article>; }
function ContentPanel({ content, ideas, onGenerate, onApprove }: { content: Row; ideas: Row[]; onGenerate: (idea: Row, format?: string) => void; onApprove: (id: string) => void }) { const [format, setFormat] = useState("short insight"); return <Section title="Content intelligence" subtitle="Generate from your profile and first-hand project context. Nothing auto-publishes."><div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 12 }}><select value={format} onChange={(e) => setFormat(e.target.value)} style={{ ...input, width: "auto", margin: 0 }}>{formats.map((f) => <option key={f}>{f}</option>)}</select></div>{ideas.map((i) => <Idea key={i.id} idea={i} onClick={() => onGenerate(i, format)} />)}<h3>Drafts</h3>{(content.drafts || []).map((d: Row) => <Draft key={d.id} draft={d} onApprove={() => onApprove(d.id)} />)}</Section>; }
function People({ rows }: { rows: Row[] }) { return <Section title="Relationship engine" subtitle="Prioritize genuine recurring relationships, not follower counts.">{rows.map((p) => <div key={p.id} style={{ ...card, marginBottom: 10 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><div><h3 style={{ margin: 0 }}>@{p.x_username}</h3><div style={{ opacity: .6 }}>{p.display_name} · {p.niche}</div></div><b>{p.relationship_status}</b></div><p>{p.interaction_count} interactions · {p.relevance_score}/100 relevance</p><div style={{ opacity: .6 }}>{p.next_action || p.notes}</div></div>)}{!rows.length && <Empty text="No relationships yet. Add real people you interact with." />}</Section>; }
function Analytics({ data }: { data: Row }) { return <Section title="Analytics" subtitle="Only real stored posts are used for account-level learning. Demo data stays isolated."><div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 10 }}><Metric label="Real posts" value={data.postsAnalyzed || 0} sub="eligible for learning" /><Metric label="Impressions" value={data.summary?.impressions || 0} sub="real" /><Metric label="Engagements" value={data.summary?.engagements || 0} sub="real" /><Metric label="Rate" value={data.summary?.engagementRate == null ? "—" : `${data.summary.engagementRate}%`} sub="real" /></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 12 }}><div style={card}><h3>Best topics</h3>{(data.topics || []).map((x: Row) => <p key={x.topic}>{x.topic} · {x.avgEngagements} avg · {x.posts} posts</p>)}</div><div style={card}><h3>Best formats</h3>{(data.formats || []).map((x: Row) => <p key={x.format}>{x.format} · {x.avgEngagements} avg · {x.posts} posts</p>)}</div></div><div style={{ ...card, marginTop: 10 }}><h3>Best posts</h3>{(data.bestPosts || []).map((x: Row) => <p key={x.x_post_id}>{x.text} · {x.engagements} engagements</p>)}{!data.postsAnalyzed && <Empty text="Not enough real data yet. Do not infer strategy from demo analytics." />}</div></Section>; }
function Learning({ data, analytics }: { data: Row; analytics: Row }) { return <Section title="Learning loop" subtitle="The system changes strategy only when the evidence is sufficient."><div style={card}><h2>{data.sufficient ? "Early signal" : "Not enough data"}</h2><p>{data.message}</p>{(data.insights || []).map((x: string) => <p key={x}>• {x}</p>)}</div><div style={{ ...card, marginTop: 10 }}><h3>What will influence future recommendations</h3><p>Topics: {(analytics.topics || []).slice(0, 5).map((x: Row) => x.topic).join(", ") || "waiting for data"}</p><p>Formats: {(analytics.formats || []).slice(0, 5).map((x: Row) => x.format).join(", ") || "waiting for data"}</p></div></Section>; }
