"use client";

import { useEffect, useMemo, useState } from "react";

type AnyRecord = Record<string, any>;
const defaultProfile = { niche: "Development + AI + Product Building + Vibe Coding", content_pillars: ["Building", "AI", "Development", "Problem solving", "Vibe coding", "Monetization", "Build in public", "Personal lessons"], tone: ["authentic", "curious", "practical", "honest", "builder-oriented", "occasionally opinionated"], avoid_topics: ["corporate language", "generic motivational content", "fake guru language", "excessive emojis", "engagement bait", "forced slang", "fake controversy"], target_followers: 1000 };

async function api<T>(url: string, options?: RequestInit): Promise<T> { const r = await fetch(url, options); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Request failed"); return d; }
const box = { background: "rgba(255,255,255,.035)", border: "1px solid rgba(255,255,255,.08)", borderRadius: 18, padding: 20 };
const btn = { border: "1px solid rgba(255,255,255,.12)", background: "rgba(255,255,255,.06)", color: "inherit", borderRadius: 10, padding: "9px 13px", cursor: "pointer" };

export default function GrowthPage() {
  const [data, setData] = useState<AnyRecord>({}); const [profile, setProfile] = useState(defaultProfile); const [tab, setTab] = useState("Today"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function load() {
    const [s, p, o, c, r, people, a, cal, l, q] = await Promise.all([
      api<AnyRecord>("/api/x/status"), api<AnyRecord>("/api/growth/profile").catch(() => ({ profile: defaultProfile })), api<AnyRecord>("/api/growth/opportunities").catch(() => ({ opportunities: [] })), api<AnyRecord>("/api/growth/content").catch(() => ({ ideas: [], drafts: [] })), api<AnyRecord>("/api/growth/replies").catch(() => ({ replies: [] })), api<AnyRecord>("/api/growth/relationships").catch(() => ({ relationships: [] })), api<AnyRecord>("/api/growth/analytics").catch(() => null), api<AnyRecord>("/api/growth/calendar").catch(() => ({ calendar: [] })), api<AnyRecord>("/api/growth/learning").catch(() => null), api<AnyRecord>("/api/growth/approval").catch(() => ({ content: [], replies: [], opportunities: [] }))
    ]);
    setData({ s, o, c, r, people, a, cal, l, q }); setProfile(p.profile || defaultProfile);
  }
  useEffect(() => { load().catch(e => setMessage(e.message)); }, []);
  const account = data.s?.account; const followers = account?.followers_count ?? 0; const goal = profile.target_followers || 1000; const progress = Math.min(100, followers / goal * 100);
  const actions = useMemo(() => (data.o?.opportunities?.length || 0) + (data.c?.ideas?.length ? 1 : 0) + (data.people?.relationships?.length ? 1 : 0), [data]);
  async function demo() { setBusy("demo"); try { const d = await api<AnyRecord>("/api/growth/demo", { method: "POST" }); setMessage(d.message); await load(); } catch(e) { setMessage(e instanceof Error ? e.message : "Demo failed"); } finally { setBusy(""); } }
  async function saveProfile() { setBusy("profile"); try { await api("/api/growth/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); setMessage("Growth profile saved."); } catch(e) { setMessage(e instanceof Error ? e.message : "Save failed"); } finally { setBusy(""); } }
  async function generateIdea(idea: AnyRecord) { setBusy(idea.id); try { await api("/api/growth/content", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "generate", idea, niche: profile.niche, experience: "my current product build", format: "short insight" }) }); setMessage("Draft created for review."); await load(); } catch(e) { setMessage(e instanceof Error ? e.message : "Generation failed"); } finally { setBusy(""); } }
  async function generateReply(o: AnyRecord) { setBusy(o.id); try { await api("/api/growth/replies", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ opportunity_id: o.id, author_username: o.author_username, topic: o.topic, source_content: o.content, niche: profile.niche }) }); setMessage("Reply suggestion created."); await load(); } catch(e) { setMessage(e instanceof Error ? e.message : "Reply failed"); } finally { setBusy(""); } }
  async function status(type: "content" | "reply", id: string, value: string) { const url = type === "content" ? "/api/growth/content" : "/api/growth/replies"; await api(url, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status: value }) }); await load(); }
  const nav = ["Today", "Opportunities", "Content", "Replies", "People", "Analytics", "Calendar", "Profile", "Approvals"];
  return <main style={{ minHeight: "100vh", padding: 28, maxWidth: 1400, margin: "auto" }}>
    <header style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 20, marginBottom: 24 }}><div><div style={{ opacity: .55, fontSize: 12, letterSpacing: 2 }}>X GROWTH AGENT</div><h1 style={{ fontSize: 34, margin: "8px 0" }}>{account ? `Good morning, ${account.name}.` : "Growth Command Center"}</h1><div style={{ opacity: .65 }}>Human-first growth toward {goal.toLocaleString()} genuine followers.</div></div><button style={btn} onClick={demo} disabled={busy === "demo"}>{busy === "demo" ? "Loading…" : "Load demo data"}</button></header>
    <nav style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 24 }}>{nav.map(n => <button key={n} style={{ ...btn, background: tab === n ? "rgba(255,255,255,.13)" : btn.background }} onClick={() => setTab(n)}>{n}</button>)}</nav>
    {message && <div style={{ ...box, marginBottom: 18 }}>{message}</div>}

    {tab === "Today" && <><section style={{ display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: 14 }}><Metric label="Followers" value={followers} sub={`${progress.toFixed(1)}% of ${goal}`} /><Metric label="Today's actions" value={actions} sub="meaningful, approval-first" /><Metric label="Streak" value="0" sub="start today" /><Metric label="Learning" value={data.l?.sufficient ? "Learning" : "Not enough data"} sub={data.l?.message || "Real post history required"} /></section><section style={{ display: "grid", gridTemplateColumns: "2fr 1fr", gap: 14, marginTop: 14 }}><div style={box}><h2>🔥 Top opportunities</h2>{(data.o?.opportunities || []).slice(0,3).map((o: AnyRecord) => <Opportunity key={o.id} o={o} onReply={() => generateReply(o)} busy={busy === o.id} />)}{!data.o?.opportunities?.length && <Empty text="No opportunities yet. Load clearly marked demo data or add a manual opportunity." />}</div><div style={box}><h2>Progress</h2><div style={{ fontSize: 44, fontWeight: 700 }}>{followers}</div><div style={{ opacity: .6 }}>followers</div><div style={{ height: 8, borderRadius: 10, background: "rgba(255,255,255,.08)", margin: "18px 0" }}><div style={{ width: `${progress}%`, height: "100%", borderRadius: 10, background: "currentColor" }} /></div><small>{goal.toLocaleString()} target</small><hr style={{ borderColor: "rgba(255,255,255,.08)", margin: "22px 0" }} /><strong>{account?.sync_status === "limited" ? "Connected · X API limited" : account ? "X connected" : "X not connected"}</strong><p style={{ opacity: .6 }}>{account?.sync_status === "limited" ? "Credits unavailable. Stored, manual and demo intelligence remains usable." : "OAuth status and data availability are tracked separately."}</p></div></section><section style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, marginTop: 14 }}><div style={box}><h2>✍️ Today's content</h2>{data.c?.ideas?.slice(0,2).map((i: AnyRecord) => <Idea key={i.id} idea={i} onGenerate={() => generateIdea(i)} busy={busy === i.id} />)}{!data.c?.ideas?.length && <Empty text="No content ideas yet." />}</div><div style={box}><h2>👥 People to engage</h2>{data.people?.relationships?.slice(0,5).map((p: AnyRecord) => <div key={p.id} style={{ display: "flex", justifyContent: "space-between", padding: "12px 0", borderBottom: "1px solid rgba(255,255,255,.06)" }}><div><b>@{p.x_username}</b><div style={{ opacity: .6 }}>{p.niche || "Builder"} · {p.interaction_count} interactions</div></div><span>{p.relationship_status}</span></div>)}{!data.people?.relationships?.length && <Empty text="No relationships tracked yet." />}</div></section></>}

    {tab === "Opportunities" && <Panel title="Opportunity engine" subtitle="Ranked by relevance, momentum, audience fit, conversation quality and your ability to add value.">{(data.o?.opportunities || []).map((o: AnyRecord) => <Opportunity key={o.id} o={o} onReply={() => generateReply(o)} busy={busy === o.id} />)}</Panel>}
    {tab === "Content" && <Panel title="Content studio" subtitle="Original, first-hand, editable. Nothing publishes automatically."><div style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 14 }}>{(data.c?.ideas || []).map((i: AnyRecord) => <Idea key={i.id} idea={i} onGenerate={() => generateIdea(i)} busy={busy === i.id} />)}</div><h3>Drafts</h3>{(data.c?.drafts || []).map((d: AnyRecord) => <article key={d.id} style={{ ...box, marginTop: 12 }}><div style={{ display: "flex", justifyContent: "space-between" }}><b>{d.format}</b><span>{d.status}</span></div><textarea defaultValue={d.body} onBlur={e => api("/api/growth/content", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: d.id, status: "draft", body: e.currentTarget.value }) })} style={{ width: "100%", minHeight: 130, margin: "12px 0", background: "transparent", color: "inherit", border: "1px solid rgba(255,255,255,.1)", borderRadius: 10, padding: 12 }} /><div style={{ display: "flex", gap: 8 }}><button style={btn} onClick={() => status("content", d.id, "saved")}>Save</button><button style={btn} onClick={() => status("content", d.id, "approved")}>Approve</button><button style={btn} onClick={() => status("content", d.id, "rejected")}>Reject</button></div></article>)}</Panel>}
    {tab === "Replies" && <Panel title="Reply intelligence" subtitle="Add value, share experience, ask meaningful questions. Avoid generic engagement bait.">{(data.r?.replies || []).map((r: AnyRecord) => <article key={r.id} style={{ ...box, marginBottom: 12 }}><b>@{r.author_username}</b><p style={{ opacity: .6 }}>{r.source_content}</p><textarea defaultValue={r.reply} onBlur={e => api("/api/growth/replies", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: r.id, status: "pending", reply: e.currentTarget.value }) })} style={{ width: "100%", minHeight: 110, background: "transparent", color: "inherit", border: "1px solid rgba(255,255,255,.1)", borderRadius: 10, padding: 12 }} /><div style={{ display: "flex", gap: 8, marginTop: 10 }}><button style={btn} onClick={() => status("reply", r.id, "saved")}>Save</button><button style={btn} onClick={() => status("reply", r.id, "approved")}>Approve</button><button style={btn} onClick={() => status("reply", r.id, "rejected")}>Reject</button></div></article>)}{!data.r?.replies?.length && <Empty text="No reply suggestions yet. Generate one from an opportunity." />}</Panel>}
    {tab === "People" && <Panel title="Relationship engine" subtitle="Build genuine recurring relationships, not follower lists.">{(data.people?.relationships || []).map((p: AnyRecord) => <div key={p.id} style={{ ...box, marginBottom: 10 }}><div style={{ display: "flex", justifyContent: "space-between" }}><div><h3 style={{ margin: 0 }}>@{p.x_username}</h3><div style={{ opacity: .6 }}>{p.display_name} · {p.niche}</div></div><b>{p.relationship_status}</b></div><p>{p.interaction_count} interactions · relevance {p.relevance_score}/100</p><div style={{ opacity: .6 }}>Last interaction: {p.last_interaction_at ? new Date(p.last_interaction_at).toLocaleDateString() : "—"}</div></div>)}</Panel>}
    {tab === "Analytics" && <Panel title="Analytics + learning" subtitle="Real stored data only. No conclusions are claimed when the sample is too small."><section style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 12 }}><Metric label="Posts analyzed" value={data.a?.postsAnalyzed ?? 0} sub={data.a?.dataStatus || "unknown"} /><Metric label="Impressions" value={data.a?.summary?.impressions ?? 0} sub="stored metrics" /><Metric label="Engagements" value={data.a?.summary?.engagements ?? 0} sub="likes + replies + reposts + quotes" /><Metric label="Rate" value={data.a?.summary?.engagementRate == null ? "—" : `${data.a.summary.engagementRate}%`} sub="not enough data = —" /></section><div style={{ ...box, marginTop: 14 }}><h3>Learning loop</h3><p>{data.l?.message || "No learning result yet."}</p>{(data.l?.insights || []).map((x: string) => <div key={x}>• {x}</div>)}</div><div style={{ ...box, marginTop: 14 }}><h3>Best stored posts</h3>{(data.a?.bestPosts || []).map((p: AnyRecord) => <div key={p.x_post_id} style={{ padding: 12, borderTop: "1px solid rgba(255,255,255,.06)" }}>{p.text}<div style={{ opacity: .6 }}>{p.engagements} engagements · {p.impressions} impressions · {p.rate == null ? "—" : `${p.rate.toFixed(2)}%`}</div></div>)}</div></Panel>}
    {tab === "Calendar" && <Panel title="Content calendar" subtitle="Plan flexibly; the calendar never publishes by itself.">{(data.cal?.calendar || []).map((x: AnyRecord) => <div key={x.id} style={{ ...box, marginBottom: 10 }}><b>{new Date(x.planned_date).toLocaleDateString()}</b> · {x.pillar} · {x.format} · {x.status}</div>)}{!data.cal?.calendar?.length && <Empty text="No planned content yet." />}</Panel>}
    {tab === "Profile" && <Panel title="Growth profile" subtitle="This context powers recommendations and content generation."><label>Niche<textarea value={profile.niche} onChange={e => setProfile({ ...profile, niche: e.target.value })} style={input} /></label><label>Content pillars<textarea value={profile.content_pillars.join(", ")} onChange={e => setProfile({ ...profile, content_pillars: e.target.value.split(",").map(x => x.trim()).filter(Boolean) })} style={input} /></label><label>Tone<textarea value={profile.tone.join(", ")} onChange={e => setProfile({ ...profile, tone: e.target.value.split(",").map(x => x.trim()).filter(Boolean) })} style={input} /></label><label>Avoid<textarea value={profile.avoid_topics.join(", ")} onChange={e => setProfile({ ...profile, avoid_topics: e.target.value.split(",").map(x => x.trim()).filter(Boolean) })} style={input} /></label><label>Follower goal<input type="number" value={profile.target_followers} onChange={e => setProfile({ ...profile, target_followers: Number(e.target.value) || 1000 })} style={input} /></label><button style={btn} onClick={saveProfile} disabled={busy === "profile"}>{busy === "profile" ? "Saving…" : "Save profile"}</button></Panel>}
    {tab === "Approvals" && <Panel title="Approval center" subtitle="One queue for content, replies and opportunities. You remain in control."><h3>Content</h3>{(data.q?.content || []).map((x: AnyRecord) => <div key={x.id} style={{ ...box, marginBottom: 8 }}>{x.body}<div style={{ marginTop: 8 }}><button style={btn} onClick={() => status("content", x.id, "approved")}>Approve</button></div></div>)}<h3>Replies</h3>{(data.q?.replies || []).map((x: AnyRecord) => <div key={x.id} style={{ ...box, marginBottom: 8 }}>@{x.author_username}: {x.reply}<div style={{ marginTop: 8 }}><button style={btn} onClick={() => status("reply", x.id, "approved")}>Approve</button></div></div>)}</Panel>}
  </main>;
}

const input: React.CSSProperties = { display: "block", width: "100%", margin: "8px 0 16px", minHeight: 42, background: "transparent", color: "inherit", border: "1px solid rgba(255,255,255,.1)", borderRadius: 10, padding: 10 };
function Metric({ label, value, sub }: { label: string; value: any; sub: string }) { return <div style={box}><div style={{ opacity: .55, fontSize: 12 }}>{label}</div><div style={{ fontSize: 30, fontWeight: 700, marginTop: 7 }}>{value}</div><div style={{ opacity: .5, fontSize: 12, marginTop: 4 }}>{sub}</div></div>; }
function Empty({ text }: { text: string }) { return <div style={{ opacity: .55, padding: "24px 0" }}>{text}</div>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section style={box}><h2 style={{ marginTop: 0 }}>{title}</h2><p style={{ opacity: .55 }}>{subtitle}</p>{children}</section>; }
function Idea({ idea, onGenerate, busy }: { idea: AnyRecord; onGenerate: () => void; busy: boolean }) { return <article style={{ ...box, marginBottom: 10 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><h3 style={{ margin: 0 }}>{idea.title}</h3><b>{idea.score}/100</b></div><p style={{ opacity: .65 }}>{idea.reason}</p><p><b>Angle:</b> {idea.angle}</p><p><b>Hook:</b> {idea.hook}</p><button style={btn} onClick={onGenerate} disabled={busy}>{busy ? "Generating…" : "Generate draft"}</button></article>; }
function Opportunity({ o, onReply, busy }: { o: AnyRecord; onReply: () => void; busy: boolean }) { return <article style={{ padding: "14px 0", borderTop: "1px solid rgba(255,255,255,.06)" }}><div style={{ display: "flex", justifyContent: "space-between" }}><div><b>@{o.author_username}</b> · {o.topic}</div><strong>{o.opportunity_score}/100</strong></div><p style={{ opacity: .7 }}>{o.content}</p><div style={{ opacity: .55 }}>{o.reason}</div><div style={{ marginTop: 8 }}><button style={btn} onClick={onReply} disabled={busy}>{busy ? "Creating…" : "Generate thoughtful reply"}</button></div></article>; }
